name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create gradlew script
      run: |
        cd HandRemiApp
        touch gradlew
        chmod +x gradlew
        echo "#!/bin/sh" > gradlew
        echo "exec gradle \"\$@\"" >> gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      working-directory: ./HandRemiApp
      run: |
        gradle wrapper
        ./gradlew build

    - name: Build Debug APK
      working-directory: ./HandRemiApp
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: HandRemiApp/app/build/outputs/apk/debug/app-debug.apk
