name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        mkdir -p HandRemiApp/gradlew
        touch HandRemiApp/gradlew
        chmod +x HandRemiApp/gradlew
        echo "#!/bin/sh" > HandRemiApp/gradlew
        echo "exec gradle \"\$@\"" >> HandRemiApp/gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      working-directory: ./HandRemiApp
      run: |
        gradle wrapper
        ./gradlew build

    - name: Build Debug APK
      working-directory: ./HandRemiApp
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: HandRemiApp/app/build/outputs/apk/debug/app-debug.apk
